export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const REDIRECTED = "REDIRECTED";
export const LOGOUT_ONCE = "LOGOUT_ONCE";
export const LOGOUT_ALL = "LOGOUT_ALL";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const CHANGE_COUNT = "CHANGE_COUNT";

export const FETCHED_POSTS = "FETCHED_POSTS";
export const ERROR_POSTS = "ERROR_POSTS";
export const DELETE_POST = "DELETE_POST";
export const UPDATE_POSTS = "UPDATE_POSTS";

export const FETCH_OTHER_PROFILE_SUCCESS = "FETCH_OTHER_PROFILE_SUCCESS";
export const FETCH_OTHER_PROFILE_FAIL = "FETCH_OTHER_PROFILE_FAIL";
export const FETCH_OTHER_POSTS_SUCCESS = "FETCH_OTHER_POSTS_SUCCESS";
export const FETCH_OTHER_POSTS_FAIL = "FETCH_OTHER_POSTS_FAIL";
export const CLEAR_OTHER_PROFILE = "CLEAR_OTHER_PROFILE";

export const UPDATE_LIKED_SUCCESS = "UPDATE_LIKED_SUCCESS";
export const UPDATE_LIKED_FAILURE = "UPDATE_LIKED_FAILURE";
export const UPDATE_LIKES_SUCCESS = "UPDATE_LIKES_SUCCESS";
export const UPDATE_LIKES_SUCCESS_OTHER = "UPDATE_LIKES_SUCCESS_OTHER";